### PR TITLE
Benchmark Matrix diagonal eigenvalues

### PR DESCRIPTION
**Pull request by sylee957**
Closes #45

Also done some refactors

### CODE REVIEW

**Comment by asmeurer** [comment]
Feel free to just merge stuff into this repo if the tests pass. We need more rigorous tests for this repo (to make sure things work with older SymPy versions for instance), but that can be fixed later.

**Comment by moorepants** [comment]
One thing we'd like to review is the time each new benchmark takes. We'd like to keep the benchmarks as fast as possible since it takes 1 to 2 days to run the suite.

**Comment by sylee957** [comment]
I believe that solving moderate size eigenvalue problems in SymPy can take insanely long hours, especially with symbolic entries.
If this test is causing such problem, we may either have to trim down the size, or only run on the commits after https://github.com/sympy/sympy/pull/15030

**Comment by moorepants** [comment]
Benchmarks should ideally be microsecond operations. Please check timing of all benchmarks before merging.

**Comment by moorepants** [comment]
Also, can we follow the same "don't merge your own PRs without review" in this repo too. Thanks.

**Comment by bjodah** [comment]
We can add inherently slow benchmarks to the `slow_benchmarks/` folder. Those won't be run regularly though...

**Pull request merged**
