### PR TITLE
Add new CSE benchmark based on Kalman filter matrix expression

### PR DESCRIPTION
**Pull request by brocksam**
Issue https://github.com/sympy/sympy/issues/24696 highlighted that CSE on matrix expressions was extremely slow because terms were eagerly evaluated during the optimisation pass. PR https://github.com/sympy/sympy/issues/24696 implemented a fix that reduces the runtime on this 2x2 example by ~10,000x, even more for larger systems. It's worth adding as a benchmark to avoid performance regressions in the future.

### CODE REVIEW

**Comment by brocksam** [comment]
Unsure whether this should be treated as a "slow" benchmark or not. Runtime is approximately ~60s. However, https://github.com/sympy/sympy/issues/24696 reduces it to ~6ms. So in the historic case it's "slow", but moving forward it'll be fast.

**Comment by brocksam** [comment]
In that case I think this is good to go from my end then.

**Comment by moorepants** [comment]
Should we wait to merge after your fix goes it? (so it doesn't just add 60 sec to the PR CI)

**Comment by brocksam** [comment]
> Should we wait to merge after your fix goes it? (so it doesn't just add 60 sec to the PR CI)

Yes, should probably wait. https://github.com/sympy/sympy/issues/24696 is ready so and appears approved by reviewers so just waiting for it to be merged, hopefully soon.

**Comment by asmeurer** [comment]
Should this be merged now?

**Comment by brocksam** [comment]
I think so, yes please.

**Pull request merged**
