### PR TITLE
Fixed error in setup.

### PR DESCRIPTION
**Pull request by moorepants**
@bjodah I missed this.

### CODE REVIEW

**Comment by bjodah** [comment]
Oh yes, I forgot that even though travis reports passing tests the actual benchmark might have failed, so one has to manually inspect the CI log.... but in this case the reported error in the CI log from the last PR show failing benchmark for `time_kanesmethod_mass_spring_dampe...` want to look into that one as well here?

**Comment by moorepants** [comment]
Just fixed it and tested it locally. To test this we'd need to write version specific tests.

**Comment by moorepants** [comment]
Sorry for merging in the bad code. I hadn't looked at it in a while and didn't test things thoroughly locally first.

**Comment by bjodah** [comment]
No worries. What makes this hard to test automatically is that failed benchmarks does not affect the exit status of `asv` (see [this](https://github.com/spacetelescope/asv/issues/296)), the people behind `asv` were not opposed to adding a flag causing `asv` to exit with failed exit status on failed benchmarks. But I couldn't justify spending time on developing a patch for `asv` at that time (and probably not right now either).

**Comment by bjodah** [comment]
Just saw that someone else wanted this behavior as well: https://github.com/spacetelescope/asv/issues/449

**Comment by certik** [comment]
@bjodah you should upvote that request on the asv repo. ;)

**Comment by bjodah** [comment]
Upvoted, thanks! :)

**Comment by moorepants** [comment]
Note that if we implement that kind of check then it is going to be real pain to write benchmarks that pass for every commit in the project's history. I'd rather they just fail gracefully for old API versions and when the functions don't even exist.

**Comment by bjodah** [comment]
Maybe there could be a flag which we can add to legacy benchmarks along the lines of (note that this is not a real thing):
```
@asv.mark.may_fail
def time_some_old_method():
    ...
```
then we could just mark old benchmarks as "allowed failures" and keep a "strict" setting in our travis config.

**Comment by moorepants** [comment]
I'm merging this. Tested locally and travis is done.

**Comment by certik** [comment]
@moorepants you should upvote that issue https://github.com/spacetelescope/asv/issues/449 as well. They might implement it if they see a lot of interest.

**Comment by moorepants** [comment]
Done

**Pull request merged**
