### PR TITLE
Add benchmarks for cholesky_solve and is_positive_definite

### PR DESCRIPTION
**Pull request by oscarbenjamin**
These benchmarks give better coverage of the performance regression
identified in https://github.com/sympy/sympy/issues/19200

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
It seems like the tests haven't run on this PR and I'm not sure why...

**Comment by moorepants** [comment]
LGTM! Thanks.

**Comment by moorepants** [comment]
I've had trouble with Travis's connection to Github (the key) disappearing on my repos and I have to re-establish the connection.

**Comment by moorepants** [comment]
@asmeurer Could check the settings on this repo to see if the Travis key is still there.

**Comment by oscarbenjamin** [comment]
I pushed a couple of bigger benchmarks and the tests ran this time round. Thanks for reviewing!

**Pull request merged**
