### PR TITLE
Add benchmarks for pycosat in logic

### PR DESCRIPTION
**Pull request by debugger22**
@bjodah Please review.

### CODE REVIEW

**Comment by bjodah** [comment]
I think it looks good. However, there is little point in merging this until `pycosat` is available in SymPy's master branch (see Traceback in the test output on travis-ci).

Until then you can use your branch `debugger22:pycosat-benchmark` for any benchmarking of potential implementations.

Send a ping here once `pycosat` is merged into `sympy` and we can restart the test to see if it works as intended.

**Comment by debugger22** [comment]
Sure.

**Comment by moorepants** [comment]
Is pycosat in SymPy now that 1.0 is released?

**Comment by moorepants** [comment]
Closing due to inactivity.

**Pull request closed without merging**
