### PR TITLE
Benchmark cse on rather small expressions

### PR DESCRIPTION
**Pull request by bjodah**
This takes 16 ms on sympy-0.7.6

### CODE REVIEW

**Comment by bjodah** [comment]
I've turned the original benchmark to a minimal reproducible parametrized test. I clearly shows the performance regression while being on the order of ~1s even for the slow code:
```
[ 33.33%] · For sympy commit hash 9670ff89:
[ 33.33%] ·· Building for virtualenv-py3.5-fastcache-mpmath......
[ 33.33%] ·· Benchmarking virtualenv-py3.5-fastcache-mpmath
[ 66.67%] ··· Running cse.TimeCSE.time_cse                                                                                                                                                                        ok
[ 66.67%] ···· 
               ========= ==========
                 param1            
               --------- ----------
                 (2, 8)   39.93ms  
                 (3, 8)   41.45ms  
                 (4, 8)   42.01ms  
                 (2, 9)   85.49ms  
                (2, 10)   455.51ms 
                (2, 11)    1.00s   
               ========= ==========

[ 66.67%] · For sympy commit hash fbb29636:
[ 66.67%] ·· Building for virtualenv-py3.5-fastcache-mpmath.....
[ 66.67%] ·· Benchmarking virtualenv-py3.5-fastcache-mpmath
[100.00%] ··· Running cse.TimeCSE.time_cse                                                                                                                                                                        ok
[100.00%] ···· 
               ========= ========
                 param1          
               --------- --------
                 (2, 8)   4.54ms 
                 (3, 8)   4.79ms 
                 (4, 8)   4.90ms 
                 (2, 9)   4.93ms 
                (2, 10)   5.53ms 
                (2, 11)   5.83ms 
               ========= ========
```

**Comment by moorepants** [comment]
This isn't for small expressions but we do have one other cse test: http://www.moorepants.info/misc/sympy-asv/#large_exprs.TimeLargeExpressionOperations.time_cse and there was a recent regression that I made the PR author aware of. Nothing has happened to it since.

**Comment by moorepants** [comment]
This is fine to merge.

**Comment by bjodah** [comment]
Thanks,

I just checked what happens when `SYMPY_CACHE_SIZE=25000`:
```
[ 33.33%] · For sympy commit hash 9670ff89:
[ 33.33%] ·· Building for virtualenv-py3.5-fastcache-mpmath......
[ 33.33%] ·· Benchmarking virtualenv-py3.5-fastcache-mpmath
[ 66.67%] ··· Running cse.TimeCSE.time_cse                                                                                                                                                                        ok
[ 66.67%] ···· 
               =============== ==========
                nexprs_nterms            
               --------------- ----------
                    (2, 8)      42.28ms  
                    (3, 8)      41.32ms  
                    (4, 8)      42.02ms  
                    (2, 9)      84.79ms  
                   (2, 10)      159.80ms 
                   (2, 11)      324.80ms 
               =============== ==========

[ 66.67%] · For sympy commit hash fbb29636:
[ 66.67%] ·· Building for virtualenv-py3.5-fastcache-mpmath......
[ 66.67%] ·· Benchmarking virtualenv-py3.5-fastcache-mpmath
[100.00%] ··· Running cse.TimeCSE.time_cse                                                                                                                                                                        ok
[100.00%] ···· 
               =============== ========
                nexprs_nterms          
               --------------- --------
                    (2, 8)      4.66ms 
                    (3, 8)      4.83ms 
                    (4, 8)      4.92ms 
                    (2, 9)      4.95ms 
                   (2, 10)      5.65ms 
                   (2, 11)      6.03ms 
               =============== ========
```
so the regression is still there.

**Pull request merged**
