### PR TITLE
Add some basic matrix expression benchmarks

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by moorepants** [comment]
Looks like the Piecewise output may have changed with the latest SymPy releases.

**Comment by oscargus** [comment]
It has. Or rather, there is better simplification of Piecewise now. Including a bug, although I do not know if the bug affects this. See https://github.com/sympy/sympy/pull/15929

**Comment by oscargus** [comment]
The code in https://github.com/sympy/sympy/pull/15929 "works", but I do not have a 2.7 installed so I do not really know how to progress with the 2.7-related problem (except installing a 2.7...). The structure should be improved as well, but once merged the simplified `Piecewise` will most likely change again.

**Comment by asmeurer** [comment]
I didn't realize there were tests here. These benchmarks are unrelated, so I'm merging this.

**Comment by bjodah** [comment]
There were some errors related to this benchmark (shouldn't the methods take self as an argument?):
```
...
TypeError: time_Mul() takes no arguments (1 given)
```

**Comment by asmeurer** [comment]
Oh crap I forgot to push that fix.

**Pull request merged**
