### PR TITLE
Parametrize 'modules' kwarg in lambdify benchmark

### PR DESCRIPTION
**Pull request by bjodah**
To partially address: https://github.com/sympy/sympy/issues/12793

~~Don't know why asv isn't picking up on `params`~~

### CODE REVIEW

**Comment by bjodah** [comment]
So here are the timing for creating the lambdified function:
```
               =========== =========

                  param1            

               ----------- ---------

                 ['math']   90.74ms 

                ['numpy']   85.93ms 

               =========== =========

```

and evaluating:
```
               =========== ==========

                  param1             

               ----------- ----------

                 ['math']   16.41μs  

                ['numpy']   399.72μs 

               =========== ==========
```
note: we expect performance conscious users to use `numba` or SymEngine.

**Comment by moorepants** [comment]
Why would numpy be significantly slower?

**Comment by moorepants** [comment]
+ 1 to merge

**Comment by bjodah** [comment]
Numpy functions will create numpy objects around Python's floats. So that's the extra overhead.

**Pull request merged**
