### PR TITLE
refactoring the core benchmarks and add arit and expand benchmarks

### PR DESCRIPTION
**Pull request by RituRajSingh878**
I am adding basic benchmarks based on the sympy test case and refactor the core benchmarks based on the sympy tests and will add other basic benchmarks in later commits and PRs.
Initially, I was confused about adding the benchmarks as I don't know what I should add in the benchmarks that will be useful, so I am following sympy tests.
If anyone has suggestions for adding benchmarks please give here.

Thanks

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I think that filenames should be lower case i.e. `arit.py` rather than `Arit.py`.

There are very few lines of code here so I'm not sure there's any need to split across multiple files at this stage. Although I suppose you are doing that to mimic the structure of the sympy codebase which is apparently the intention for the benchmarks...

Does anyone have any opinions about this?

**Comment by oscarbenjamin** [comment]
This will be fine to merge if you change the filename to lower case

**Comment by RituRajSingh878** [comment]
> This will be fine to merge if you change the filename to lower case

I will change the file name and will add more benchmarks to it.

**Comment by RituRajSingh878** [comment]
if it is okay then you can merge it. I will open new PRs for other benchmarks.

**Comment by oscarbenjamin** [comment]
I don't think so many blank lines are needed in test_arit. Otherwise this is good.

**Comment by oscarbenjamin** [comment]
Looks good. Thanks

**Pull request merged**
