### PR TITLE
Added benchmark of Sum.doit() related to issue #11030

### PR DESCRIPTION
**Pull request by dibus2**
This is the benchmark with the call to doit on symbolic sum that is much slower on version 1.0 versus old version 0.7.2. Seems like piecewise_fold is where the time is spent.

### CODE REVIEW

**Comment by bjodah** [comment]
@dibus2 so we are almost there, you just need to create a class called TimeSomethong with a setup and a time_something method, e.g.:

```
class TimeSum:

    def setup(self):
        self.expr = Sum(...)

    def time_doit(self):
        self.expr.doit()
```
save the changes, and run
```
$ git commit -am "Added TimeClass"
$ git push
```

**Comment by dibus2** [comment]
Ok, hope it is better now. 

F.

**Comment by bjodah** [comment]
Great, the `doit()` method ran in 23ms on the CI server.
Thank you for the benchmark, now we will let the benchmark servers run through the commits of sympy.

**Comment by moorepants** [comment]
The Sum.doit benchmark is live: http://www.moorepants.info/misc/sympy-asv/#

**Pull request merged**
